### ISSUE TITLE
How to customize or override views?

### ISSUE THREAD

**Issue by tekord** [artkonekt/appshell#10]
Is it possible to customize or override views? Documentations provides info only for asset customization.

**Comment by fulopattila122** [comment]
Yes it's possible. Actually it's a Laravel feature:
https://laravel.com/docs/5.7/packages#views (scroll down to "Overriding Package Views").

It means that you can customize any appshell view if you put your customized version of the blade file(s) within your applications `resources/views/vendor/appshell` folder (has to be same folder/filename as the original). Laravel will pick it up from there instead of the original package version.

**Comment by tekord** [comment]
Thank you!
